name: 'Pull Request checker'
description: 'Github action to check PR existence before merging another PR'
inputs:
  github_token:
    description: 'A github token to give more permission than default github action permissions'
    required: false    
  head_ref:
    description: 'The branch that must be merged in the default_ref branch before be merged in the base_ref branch'
    required: true
  base_ref:
    description: 'The branch where merge is only possible if the head_ref branch is merged in the default branch'
    required: true      
  default_ref:
    description: 'The branch where head_ref branch must be merged before other merges'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
